version: '3.5'

services:
  postgres:
    container_name: postgres_demo
    network_mode: host
    image: postgres:latest
    environment:
      POSTGRES_USER: super_admin
      POSTGRES_PASSWORD: 12345
      PGDATA: /data/postgres
    volumes:
      - ./postgres-db:/data/postgres